# Generated by Django 3.2.14 on 2022-12-11 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=20, verbose_name='Categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=20, verbose_name='Nombre de Usuario')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=30, verbose_name='Apellido')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=20, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=30, verbose_name='Modelo')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripción')),
                ('puertas', models.CharField(max_length=1)),
                ('precio', models.FloatField()),
                ('fecha_publicacion', models.DateField(verbose_name='Fecha publicación')),
                ('seleccionado', models.BooleanField(default=None, null=True)),
                ('imagen', models.ImageField(default=None, null=True, upload_to='upload/', verbose_name='Imagen:')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.categoria', verbose_name='Categoría')),
            ],
        ),
    ]
