# Generated by Django 3.2 on 2022-11-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehiculoForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=30)),
                ('anio', models.IntegerField()),
                ('categoria', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=300)),
                ('puertas', models.CharField(max_length=1)),
                ('precio', models.FloatField()),
                ('fecha_publicacion', models.DateField()),
            ],
        ),
    ]
