# Generated by Django 3.2 on 2022-12-26 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='fecha_publicacion',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Fecha publicación'),
        ),
    ]
