# Generated by Django 4.1.2 on 2022-12-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=20, verbose_name='Apellido')),
                ('correo', models.CharField(max_length=20, verbose_name='Correo')),
                ('mensaje', models.CharField(max_length=240, verbose_name='Mensaje')),
            ],
        ),
    ]
