# Generated by Django 3.2 on 2022-12-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='correo',
            field=models.CharField(max_length=150, verbose_name='Correo'),
        ),
    ]
