# Generated by Django 3.2 on 2022-12-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_contacto_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='seleccionado',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
