# Generated by Django 3.2 on 2022-12-15 14:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_vehiculo_seleccionado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='fecha_publicacion',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha publicación'),
        ),
    ]
