# Generated by Django 3.2 on 2022-12-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_alter_categoria_creacion_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='modificacion_usuario',
            field=models.IntegerField(null=True),
        ),
    ]
