# Generated by Django 3.2 on 2022-12-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_categoria_modificacion_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='creacion_usuario',
            field=models.IntegerField(),
        ),
    ]
