# Generated by Django 3.2 on 2022-12-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_alter_categoria_creacion_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='eliminacion_fecha',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='eliminacion_usuario',
            field=models.IntegerField(null=True),
        ),
    ]
