# Generated by Django 3.2 on 2022-12-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0013_auto_20221229_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='categoria',
            field=models.CharField(max_length=20, unique=True, verbose_name='Categoría'),
        ),
    ]
